

import { JsonDecoder } from "ts.data.json";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: entity/image/payload/v1/image_created.proto
/* eslint-disable */
export const protobufPackage = "faceblur.entity.image.payload.v1";
export interface ImageCreatedPayload {
    imageId: string;
}




export const ImageCreatedPayloadDecoder = JsonDecoder.object(
    {
		imageId: JsonDecoder.string,
    },
    "ImageCreatedPayload"
);




